//go:build ignore

// Command generate_character_assets compiles the design-time character layout
// into Go source. The application never reads characters_svg/items.json.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"
)

type sourceDocument struct {
	Grid struct {
		Width  int `json:"width"`
		Height int `json:"height"`
	} `json:"grid"`
	Shapes []sourceShape `json:"shapes"`
}

type sourceShape struct {
	Category             string            `json:"category"`
	Asset                string            `json:"asset"`
	X                    int               `json:"x"`
	Y                    int               `json:"y"`
	Width                int               `json:"width"`
	Height               int               `json:"height"`
	ASCIIPixels          []string          `json:"asciiPixels"`
	ColorRoles           map[string]string `json:"colorRoles,omitempty"`
	BackgroundColorRoles map[string]string `json:"backgroundColorRoles,omitempty"`
}

type authoredEyesDocument struct {
	Format string        `json:"format"`
	Eyes   []sourceShape `json:"eyes"`
}

func main() {
	input, err := os.ReadFile("characters_svg/items.json")
	if err != nil {
		fatal(err)
	}
	var document sourceDocument
	if err := json.Unmarshal(input, &document); err != nil {
		fatal(err)
	}
	if document.Grid.Width != 24 || document.Grid.Height != 18 || len(document.Shapes) != 128 {
		fatal(fmt.Errorf("unexpected character layout: %dx%d, %d shapes", document.Grid.Width, document.Grid.Height, len(document.Shapes)))
	}
	mergeAuthoredEyes(&document)
	for shapeIndex := range document.Shapes {
		if document.Shapes[shapeIndex].Category == "head" {
			for rowIndex, row := range document.Shapes[shapeIndex].ASCIIPixels {
				document.Shapes[shapeIndex].ASCIIPixels[rowIndex] = fillContour(row)
			}
		}
	}
	encoded, err := json.Marshal(document)
	if err != nil {
		fatal(err)
	}
	if strings.ContainsRune(string(encoded), '`') {
		fatal(fmt.Errorf("character layout contains a backtick and cannot use a Go raw string"))
	}
	output := "// Code generated by go run ./tools/generate_character_assets.go; DO NOT EDIT.\n\npackage main\n\nconst introductionAssetLayoutJSON = `" + string(encoded) + "`\n"
	if err := os.WriteFile("character_assets_data.go", []byte(output), 0o644); err != nil {
		fatal(err)
	}
}

func mergeAuthoredEyes(document *sourceDocument) {
	input, err := os.ReadFile("eyes.json")
	if err != nil {
		fatal(fmt.Errorf("read authored eyes: %w", err))
	}
	var authored authoredEyesDocument
	if err := json.Unmarshal(input, &authored); err != nil {
		fatal(fmt.Errorf("decode authored eyes: %w", err))
	}
	if authored.Format != "keynope-eyes-v1" || len(authored.Eyes) != 16 {
		fatal(fmt.Errorf("unexpected authored eyes document %q with %d eyes", authored.Format, len(authored.Eyes)))
	}
	byAsset := make(map[string]sourceShape, len(authored.Eyes))
	for _, eye := range authored.Eyes {
		if eye.Asset == "" || eye.Width < 1 || eye.Height < 1 || len(eye.ASCIIPixels) != eye.Height {
			fatal(fmt.Errorf("authored eye %q has invalid dimensions", eye.Asset))
		}
		if _, exists := byAsset[eye.Asset]; exists {
			fatal(fmt.Errorf("authored eye %q is duplicated", eye.Asset))
		}
		if eye.X < 0 || eye.Y < 0 || eye.X+eye.Width > document.Grid.Width || eye.Y+eye.Height > document.Grid.Height {
			fatal(fmt.Errorf("authored eye %q is outside the %dx%d portrait", eye.Asset, document.Grid.Width, document.Grid.Height))
		}
		for rowIndex, row := range eye.ASCIIPixels {
			if len([]rune(row)) > eye.Width {
				fatal(fmt.Errorf("authored eye %q row %d exceeds width %d", eye.Asset, rowIndex, eye.Width))
			}
		}
		validateColorRoles(eye.Asset, "foreground", eye.ColorRoles, eye.Width, eye.Height)
		validateColorRoles(eye.Asset, "background", eye.BackgroundColorRoles, eye.Width, eye.Height)
		eye.Category = "eyes"
		byAsset[eye.Asset] = eye
	}
	for index := range document.Shapes {
		shape := &document.Shapes[index]
		if shape.Category != "eyes" {
			continue
		}
		eye, ok := byAsset[shape.Asset]
		if !ok {
			fatal(fmt.Errorf("authored eye %s is missing", shape.Asset))
		}
		*shape = eye
		delete(byAsset, shape.Asset)
	}
	if len(byAsset) != 0 {
		fatal(fmt.Errorf("authored eyes contain %d unknown assets", len(byAsset)))
	}
}

func validateColorRoles(asset, kind string, roles map[string]string, width, height int) {
	for coordinate, role := range roles {
		xText, yText, ok := strings.Cut(coordinate, ",")
		if !ok || role == "" {
			fatal(fmt.Errorf("authored eye %q has invalid %s role %q", asset, kind, coordinate))
		}
		x, xErr := strconv.Atoi(xText)
		y, yErr := strconv.Atoi(yText)
		if xErr != nil || yErr != nil || x < 0 || x >= width || y < 0 || y >= height {
			fatal(fmt.Errorf("authored eye %q has out-of-bounds %s role %q", asset, kind, coordinate))
		}
	}
}

func fillContour(row string) string {
	glyphs := []rune(row)
	left, right := -1, -1
	for index, glyph := range glyphs {
		if glyph != ' ' {
			if left < 0 {
				left = index
			}
			right = index
		}
	}
	if left < 0 {
		return row
	}
	for index := left + 1; index < right; index++ {
		if glyphs[index] == ' ' {
			glyphs[index] = '█'
		}
	}
	return string(glyphs)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "generate character assets:", err)
	os.Exit(1)
}
