const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync('main.go', 'utf8');
const start = source.indexOf('function validEngagementDots(');
const end = source.indexOf('function finishBalancedPairs(', start);
const context = vm.createContext({crypto:require('node:crypto').webcrypto});
vm.runInContext(source.slice(start, end), context);
const plain = value => JSON.parse(JSON.stringify(value));
const def = {options:['A','B','C'], dotBudget:3, stackDots:false};
assert.deepEqual(plain(context.validEngagementDots(def,[1,1,0])),[1,1,0]);
for (const dots of [[2,0,0],[-1,1,0],[1.5,0,0],[1,1],[4,0,0],['1',0,0]]) assert.equal(context.validEngagementDots(def,dots),null);
assert.deepEqual(plain(context.validEngagementDots({...def,stackDots:true},[3,0,0])),[3,0,0]);
assert.equal(context.validEngagementDots({...def,stackDots:true},[3,1,0]),null);
const pairing = (members,times) => plain(context.balancedCompletionGroups(members,times,()=>0));
assert.deepEqual(pairing(['a','b','c','d'],{a:1,b:2,c:3,d:4}),[['a','d'],['b','c']]);
assert.deepEqual(pairing(['a','b','c','d','e'],{a:1,b:2,c:3,d:4,e:5}),[['a','e'],['b','c','d']]);
assert.deepEqual(pairing(['a','b','c','d'],{a:1,b:2}),[['a','c'],['b','d']]);
for(let n=0;n<30;n++) {
  const members=Array.from({length:n},(_,i)=>String(i)), groups=pairing(members,{});
  assert.deepEqual(groups.flat().sort(),members.sort());
  if(n>1)assert.ok(groups.every(group=>group.length>=2&&group.length<=3));
}
console.log('Dot budget and completion pairing checks passed.');
vm.runInContext(fs.readFileSync('web/activity-games.js','utf8'),context);
const games=context.KeynopeGames;
const runtime=kind=>({definition:{kind,options:['*A','B'],named:false},phase:1,memberNames:{a:'Alice',b:'Bob',c:'Charlie',d:'Dennis'}});
const event=(id,response,key=Math.random().toString())=>({id:key,identity:id,payload:{response}});
let r=runtime('three');
for(const id of ['a','a','b','c','d'])games.receive(r,event(id,{text:id}));
assert.equal(r.game.entries.length,3);assert.equal(r.phase,2);
r=runtime('ball');games.receive(r,event('a',{volunteer:true}));games.receive(r,event('a',{volunteer:true}));assert.equal(r.game.volunteers.length,1);
r.game.speaker='b';r.game.stage='play';games.receive(r,event('a',{target:'a'}));assert.equal(r.game.speaker,'b');games.receive(r,event('b',{target:'a'}));assert.equal(r.game.speaker,'a');
r=runtime('ball');games.next(r);assert.equal(r.game.stage,'join');
games.receive(r,event('a',{volunteer:true}));games.receive(r,event('b',{volunteer:true}));
games.next(r);assert.equal(r.game.stage,'play');assert.equal(r.phase,1);assert(['a','b'].includes(r.game.speaker));assert(!r.game.volunteers.includes(r.game.speaker));
const first=r.game.speaker,second=r.game.volunteers[0];
games.receive(r,event(first,{end:true}));assert.equal(r.game.stage,'play');
games.receive(r,event('c',{volunteer:true}));assert(r.game.volunteers.includes('c'));
games.receive(r,event('d',{target:second}));assert.equal(r.game.speaker,first);
games.receive(r,event(first,{target:second}));assert.equal(r.game.speaker,second);assert(!r.game.volunteers.includes(second));
games.receive(r,event(second,{target:'c'}));assert.equal(r.game.speaker,'c');assert.equal(r.game.volunteers.length,0);
games.receive(r,event('d',{end:true}));assert.equal(r.game.stage,'play');
games.receive(r,event('c',{end:true}));assert.equal(r.game.stage,'done');assert.equal(r.phase,3);
games.receive(r,event('d',{volunteer:true}));assert.equal(r.game.volunteers.length,0);
r=runtime('hunt');games.receive(r,event('a',{choices:[0]}));assert.equal(games.publicState(r).entries.length,0);assert.deepEqual(plain(games.definition(r).options),['A','B']);r.phase=3;assert.deepEqual(plain(games.publicState(r).expected),[0]);assert.equal(games.publicState(r).entries[0].name,'');
r=runtime('fame');games.receive(r,event('a',{target:'Bob',text:'Thanks'}));assert.equal(games.publicState(r).entries.length,0);r.phase=3;assert.equal(games.publicState(r).entries.length,1);
console.log('Workshop state, privacy and authorization checks passed.');
for(const count of [1,3,4,8]){
  r=runtime('chosen');r.definition.chosenCount=count;r.deadlineMs=Date.now()+1000;r.pausedRemainingMs=100;
  games.next(r);
  assert.equal(r.phase,3);assert.equal(r.game.chosen.length,Math.min(count,4));
  assert.equal(new Set(r.game.chosen.map(p=>p.identity)).size,r.game.chosen.length);
  assert(r.game.chosen.every(p=>r.memberNames[p.identity]===p.displayName));
  assert.equal(r.deadlineMs,0);assert.equal(r.pausedRemainingMs,0);
  const saved=JSON.stringify(r.game.chosen);
  r.memberNames.e='Late joiner';games.next(r);games.receive(r,event('e',{chosen:['e']}));
  assert.equal(JSON.stringify(r.game.chosen),saved);
  assert.equal(JSON.stringify(games.publicState(r).chosen),saved);
  assert.equal(r.groups,undefined,'Random selection must not create pairing channels');
  r.phase=1;delete r.game;games.next(r);assert.equal(r.game.poolSize,5);
}
r=runtime('chosen');r.memberNames={};r.deadlineMs=1;games.next(r);
assert.equal(r.phase,1);assert.equal(r.deadlineMs,0);assert.equal(r.game.chosen,undefined);
r.memberNames.a='Alice';games.next(r);assert.equal(r.game.chosen[0].displayName,'Alice');
console.log('The Chosen: distinct picks, count limits, empty pool, late joins, stable reveal and reset passed.');
r=runtime('pressure');r.definition.timerSeconds=120;r.deadlineMs=Date.now()+120000;
games.receive(r,event('a',{text:'ignored'}));assert.equal(r.phase,1);assert.equal(r.game.entries.length,0);
games.next(r);assert.equal(r.phase,3);assert.equal(r.deadlineMs,0);assert.equal(r.pausedRemainingMs,0);
games.next(r);assert.equal(r.phase,3);
assert.equal(games.timerGlyphs['1'][0].length,games.timerGlyphs['0'][0].length);
console.log('Pressure Cooker: stop/expiry is terminal, no responses, consistent timer digit widths.');
assert.equal(games.has('metaphor'),false);
r=runtime('gallery');r.definition.named=true;
games.receive(r,event('a',{item:0,symbol:'?',text:'Why this design?'}));
games.receive(r,event('b',{item:1,symbol:'★',text:'Clear explanation'}));
games.receive(r,event('b',{item:1,symbol:'★',text:'   '}));
assert.equal(r.game.entries.length,2);
for(const phase of [1,2]){r.phase=phase;const state=games.publicState(r);assert.equal(state.entries.length,0);assert.deepEqual(plain(state.galleryCounts),[1,1]);assert(!JSON.stringify(state).includes('Why this design?'));}
r.phase=3;assert.equal(games.publicState(r).entries[0].name,'Alice');
r.definition.named=false;assert.equal(games.publicState(r).entries[0].name,'');
console.log('Gallery collection privacy, counts, reveal and removed activity checks passed.');
