const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.argv[2]);
  await page.waitForFunction(()=>typeof window.keynopeOpenParticipantTabs==='function');
  assert.equal(await page.locator('.keynope-settings-menu').count(),0,'Mac Settings must not appear in the editor toolbar');
  await page.evaluate(()=>window.keynopeOpenParticipantTabs());
  assert.equal(await page.locator('.keynope-tabs-overlay').count(),0,'Tabs remain unavailable without activities');
  await page.evaluate(async()=>{const r=await fetch('/api/editor/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'set-engagement',engagementData:{id:'test-tabs',kind:'pulse',prompt:'Ready?'}})});if(!r.ok)throw Error(await r.text());});
  await page.waitForTimeout(1000);
  assert(await page.evaluate(()=>{window.keynopeOpenParticipantTabs();return !!document.querySelector('.keynope-tabs-overlay');}),'native menu callback opens Tabs');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('button',{name:'Add text',exact:true}).click();
  const size=page.getByRole('spinbutton',{name:'TrueType font size',exact:true});
  await size.waitFor();
  assert.equal(await size.inputValue(),'97');
  assert(await page.evaluate(()=>document.fonts.load('20px KeynopeC64').then(f=>f.length>0)));
  const outline=await page.evaluate(async()=>{
    await KeynopeTrueType.ready;
    const canvas=document.createElement('canvas');canvas.width=600;canvas.height=240;
    const context=canvas.getContext('2d'),line={row:50,col:50,parts:[{color:'#00ff00'}],trueType:{text:'TEST',size:100,width:450,height:140,query:'render=truetype&outline=1'}};
    const topPixels=()=>{const pixels=context.getImageData(0,0,600,50).data;let count=0;for(let i=3;i<pixels.length;i+=4)if(pixels[i]>0)count++;return count;};
    KeynopeTrueType.draw(context,line,1,1,1920,1080,null);const outlined=topPixels();
    const preview=canvas.toDataURL();context.clearRect(0,0,600,240);line.trueType.query='render=truetype';KeynopeTrueType.draw(context,line,1,1,1920,1080,null);
    return {outlined,plain:topPixels(),preview};
  });
  assert(outline.outlined>0,'outline extends above the text box');assert.equal(outline.plain,0,'glyph position stays unchanged');
  fs.mkdirSync('output/truetype-audit',{recursive:true});fs.writeFileSync('output/truetype-audit/outline.png',Buffer.from(outline.preview.split(',')[1],'base64'));
  assert.match(await size.evaluate(e=>getComputedStyle(e).fontFamily),/KeynopeC64/);
  const typography=await page.evaluate(()=>{
    const line={trueType:{text:'ONE TWO THREE\nFOUR FIVE SIX\nSHORT',size:30,width:500,height:200,query:'render=truetype&align=justify'}};
    const m=KeynopeTrueType.metrics(line,1920,1080);
    const fit=KeynopeTrueType.initialBounds('TrueType text',72,245,56);
    return {widths:m.rows.map(r=>r.inkWidth),positions:m.rows[0].positions,fit};
  });
  assert(Math.abs(typography.widths[0]-500)<.001,'justify stretches comparable lines');
  assert(Math.abs(typography.widths[1]-500)<.001);
  assert(typography.widths[2]<100,'short lines remain unstretched');
  assert(typography.positions[4]-typography.positions[3]>24,'caret mapping includes justified spaces');
  assert(typography.fit.height<10&&typography.fit.width<110,'initial box fits text instead of using oversized defaults');
  const bullets=await page.evaluate(()=>{
    const line={trueType:{kind:'bullet',text:'First bullet wraps onto another line\nSecond bullet',size:30,width:300,height:240,query:'render=truetype'}};
    const m=KeynopeTrueType.metrics(line,1920,1080);
    return {advance:m.advance,rows:m.rows.map(r=>({start:r.start,end:r.end,x:r.positions[0],bullet:r.bullet,text:r.text}))};
  });
  assert(bullets.rows.length>=2,'TTF bullets retain separate lines');
  assert(bullets.rows.every(r=>r.x===bullets.advance*2),'all continuation rows use hanging indentation');
  assert.equal(bullets.rows.filter(r=>r.bullet).length,2,'one marker per bullet, not per wrapped row');
  await size.fill('120');await size.press('Tab');
  await page.waitForFunction(()=>document.querySelector('.keynope-ttf-size')?.value==='120');
  await page.getByRole('button',{name:'Edit text',exact:true}).click();
  const input=page.getByRole('textbox',{name:'Edit element text',exact:true});
  await input.fill('TRUE TYPE\nC64 TEXT');
  await page.getByRole('button',{name:'Commit',exact:true}).click();
  await input.waitFor({state:'detached'});
  await page.waitForTimeout(700);
  const state=await page.evaluate(()=>fetch('/api/editor/state').then(r=>r.json()));
  const elements=state.slides[state.current].elements;
  assert(elements.some(e=>e.text==='Original block text'&&e.query?.includes('truetype')));
  assert(elements.some(e=>e.text==='TRUE TYPE\nC64 TEXT'&&e.query.includes('ttf-size=120')));
  fs.mkdirSync('output/truetype-audit',{recursive:true});
  await page.screenshot({path:'output/truetype-audit/editor.png',fullPage:true});
  const index=elements.findIndex(e=>e.text==='TRUE TYPE\nC64 TEXT');
  const hit=page.locator('.keynope-canvas-element[data-element="'+index+'"]');
  await hit.click();await size.waitFor();
  let box=await hit.boundingBox();
  await page.mouse.move(box.x+20,box.y+20);await page.mouse.down();
  await page.mouse.move(box.x+60,box.y+40,{steps:8});await page.mouse.up();
  await page.waitForTimeout(500);
  const handle=page.locator('.keynope-canvas-element.active .keynope-resize-handle.se');
  box=await handle.boundingBox();assert(box,'resize handle');
  await page.mouse.move(box.x+4,box.y+4);await page.mouse.down();
  await page.mouse.move(box.x+80,box.y+60,{steps:8});await page.mouse.up();
  await page.waitForTimeout(500);
  assert.equal(Number(await size.inputValue()),120,'corner resize preserves font size');
  const resized=await page.evaluate(()=>fetch('/api/editor/state').then(r=>r.json()));
  const resizedQuery=new URLSearchParams(resized.slides[resized.current].elements.find(e=>e.text==='TRUE TYPE\nC64 TEXT').query);
  const originalQuery=new URLSearchParams(elements[index].query);
  assert(Number(resizedQuery.get('width'))>Number(originalQuery.get('width')),'corner resize increases available width');
  assert(Number(resizedQuery.get('height'))>Number(originalQuery.get('height')),'corner resize increases available height');
  await size.fill('72');await size.press('Tab');await page.waitForTimeout(300);
  await page.getByRole('tab',{name:'Style',exact:true}).click();
  await page.getByRole('button',{name:'Add gradient',exact:true}).click();
  await page.getByRole('menuitemradio',{name:'Horizontal',exact:true}).click();
  await page.getByRole('button',{name:'Add shadow',exact:true}).click();
  await page.getByRole('menuitemradio',{name:'Hard',exact:true}).click();
  await page.getByRole('button',{name:'Add outline',exact:true}).click();
  await page.getByRole('button',{name:'Enable see through',exact:true}).click();
  await page.waitForTimeout(500);
  // Exercise the same workspace delivery used by the browser bridge; this
  // HTTP harness has no native companion process to broadcast its new pages.
  await page.evaluate(async()=>keynopeLoadWebWorkspace(await fetch('/test/workspace').then(r=>r.json())));
  await page.waitForTimeout(200);
  await page.screenshot({path:'output/truetype-audit/effects.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Native editor: standard text insertion, UI font, numeric resize, live editing, commit, effects and migration passed.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
