const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.argv[2]||'http://127.0.0.1:8119/editor/');
  await page.locator('.keynope-web-loading').waitFor({state:'detached',timeout:60000});
  await page.getByRole('button',{name:'Add TrueType text (experimental)',exact:true}).click();
  const size=page.getByRole('spinbutton',{name:'TrueType font size',exact:true});await size.waitFor();
  const inserted=await page.evaluate(()=>deck.pages.flatMap(p=>p.lines).find(l=>l.trueType)?.trueType);
  assert(inserted.height<10&&inserted.width<110,'new TTF starts with a tight box');
  await size.fill('96');await size.press('Tab');
  await page.getByRole('button',{name:'Add gradient',exact:true}).click();await page.getByRole('menuitemradio',{name:'Horizontal',exact:true}).click();
  await page.getByRole('button',{name:'Add shadow',exact:true}).click();await page.getByRole('menuitemradio',{name:'Soft',exact:true}).click();
  await page.getByRole('button',{name:'Add outline',exact:true}).click();
  await page.getByRole('button',{name:'Enable see through',exact:true}).click();
  await page.waitForFunction(()=>deck.pages.some(p=>p.lines.some(l=>l.trueType?.size===96&&l.trueType.query.includes('transparent=1')&&l.trueType.query.includes('shadow=soft'))));
  await page.waitForTimeout(300);
  fs.mkdirSync('output/truetype-audit',{recursive:true});await page.screenshot({path:'output/truetype-audit/web.png',fullPage:true});
  const active=page.locator('.keynope-canvas-element.active'),handle=active.locator('.keynope-resize-handle.se');
  const before=await page.evaluate(()=>deck.pages.flatMap(p=>p.lines).find(l=>l.trueType).trueType);
  const box=await handle.boundingBox();assert(box);await page.mouse.move(box.x+4,box.y+4);await page.mouse.down();await page.mouse.move(box.x+70,box.y+45,{steps:8});
  await page.waitForFunction(before=>deck.pages.some(p=>p.lines.some(l=>l.trueType?.width>before.width&&l.trueType.height>before.height&&l.trueType.size===96)),before,{timeout:10000});await page.mouse.up();
  await page.waitForTimeout(400);
  assert.equal(Number(await size.inputValue()),96,'font size unchanged after drop');
  const expanded=await page.evaluate(()=>{const l=deck.pages.flatMap(p=>p.lines).find(l=>l.trueType);return {width:l.trueType.width,rows:KeynopeTrueType.metrics(l,deck.cols,deck.rows).rows.length};});
  const shrink=await handle.boundingBox();await page.mouse.move(shrink.x+4,shrink.y+4);await page.mouse.down();await page.mouse.move(shrink.x-300,shrink.y+4,{steps:8});
  await page.waitForFunction(before=>{const l=deck.pages.flatMap(p=>p.lines).find(l=>l.trueType);return l.trueType.width<before.width&&l.trueType.size===96&&KeynopeTrueType.metrics(l,deck.cols,deck.rows).rows.length>before.rows;},expanded,{timeout:10000});await page.mouse.up();
  await page.waitForTimeout(400);
  assert.equal(Number(await size.inputValue()),96,'narrowing rewraps without resizing glyphs');
  await page.getByRole('button',{name:'Justify text',exact:true}).click();
  await page.waitForFunction(()=>deck.pages.some(p=>p.lines.some(l=>l.trueType&&new URLSearchParams(l.trueType.query).get('align')==='justify')));
  for(const orientation of ['cw','down','ccw','']){
    await page.getByRole('button',{name:'Rotate',exact:true}).click();
    await page.waitForFunction(orientation=>deck.pages.some(p=>p.lines.some(l=>l.trueType&&(new URLSearchParams(l.trueType.query).get('orientation')||'')===orientation)),orientation);
    assert.equal(Number(await size.inputValue()),96,'rotation preserves font size');
    const dimensions=await page.evaluate(()=>{const l=deck.pages.flatMap(p=>p.lines).find(l=>l.trueType),m=KeynopeTrueType.metrics(l,deck.cols,deck.rows);return {w:m.width,h:m.height,bw:m.boxWidth,bh:m.boxHeight};});
    assert.equal(dimensions.w,orientation==='cw'||orientation==='ccw'?dimensions.bh:dimensions.bw);
    if(orientation==='cw')await page.screenshot({path:'output/truetype-audit/rotated.png',fullPage:true});
  }
  await active.click({button:'right'});
  await page.getByRole('button',{name:'Rotate',exact:true}).last().click();
  await page.waitForFunction(()=>deck.pages.some(p=>p.lines.some(l=>l.trueType&&l.trueType.query.includes('orientation=cw'))));
  await page.getByRole('button',{name:'Delete element',exact:true}).last().click();
  await page.waitForFunction(()=>!deck.pages.some(p=>p.lines.some(l=>l.trueType)));
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await page.waitForFunction(()=>deck.pages.some(p=>p.lines.some(l=>l.trueType)));
  const index=await page.evaluate(async()=>{const s=await fetch('/api/editor/state').then(r=>r.json());return s.slides[s.current].elements.findIndex(e=>new URLSearchParams(e.query).get('render')==='truetype');});
  await page.locator('.keynope-canvas-element[data-element="'+index+'"]').click();
  await page.getByRole('button',{name:'Convert to plain text',exact:true}).click();
  await page.waitForFunction(()=>!deck.pages.some(p=>p.lines.some(l=>l.trueType)));
  await page.getByRole('button',{name:'Convert to TrueType text',exact:true}).click();
  await page.waitForFunction(()=>deck.pages.some(p=>p.lines.some(l=>l.trueType)));
  await page.getByRole('button',{name:'Done',exact:true}).click();
  await page.getByRole('button',{name:'Add code',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Convert to heading 1',exact:true}).count(),0,'no H1 for code');
  assert.equal(await page.getByRole('button',{name:'Convert to heading 2',exact:true}).count(),0,'no H2 for code');
  const code=await page.evaluate(async()=>{const s=await fetch('/api/editor/state').then(r=>r.json());return s.slides[s.current].elements[s.selected].text;});
  await page.getByRole('button',{name:'Convert to TrueType text',exact:true}).click();
  await page.waitForFunction(code=>deck.pages.some(p=>p.lines.some(l=>l.trueType?.text===code)),code);
  assert.equal(await page.getByRole('button',{name:'Convert to TrueType text',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'Use glyph text',exact:true}).click();
  await page.waitForFunction(async()=>{const s=await fetch('/api/editor/state').then(r=>r.json());const e=s.slides[s.current].elements[s.selected];return e.kind==='code'&&new URLSearchParams(e.query).get('render')!=='truetype';});
  assert.equal(await page.getByRole('button',{name:'Use glyph text',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'Convert to TrueType text',exact:true}).click();
  await page.waitForFunction(()=>deck.pages.some(p=>p.lines.some(l=>l.trueType?.kind==='code')));
  await page.getByRole('button',{name:'Convert to bullet points',exact:true}).click();
  await page.waitForFunction(()=>deck.pages.some(p=>p.lines.some(l=>l.trueType?.kind==='bullet')));
  assert.equal(await page.getByRole('button',{name:'Convert to heading 1',exact:true}).count(),0,'no H1 for bullets');
  await page.getByRole('button',{name:'Convert to code block',exact:true}).click();
  await page.waitForFunction(()=>deck.pages.some(p=>p.lines.some(l=>l.trueType?.kind==='code')));
  assert.deepEqual(errors,[]);console.log('WASM: fitted insertion, fixed-size box resizing, rotation, justification, T/TT and code conversion, effects, deletion and undo passed.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
